name: qualitycoder
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60558
title: "QualityCoder's Test Site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bfc292'
    - '#3f4519'
    - '#8b8e4b'
    - '#636531'
  brandStrength: 0.7967647237237543
  lightness: 0.12298735976219177
  saturation: 0.542417831486091
  rhythmicContrast: 0.38577986345626414
purpose: []
